const activityData = {
    Praying: {
        name: "Praying📿",
        tag: "Praying",
        place: "door-entrance-church",
        stats: ["energy", "happiness"],
        increment: [3, 3],
        time: 5,
        type: "map",
        effect: "/assets/effect/pray.gif",
        soundEffect: "/assets/effect/praySfx.mp3",
    },
    MealWithFriend: {
        place: "Meal With Friend🍽️",
        tag: "MealWithFriend",
        stats: ["experience", "happiness", "hunger", "energy"],
        increment: [20, 20, 20, 20],
        time: 5,
        type: "tavern",
    },
    BuyFood: {
        name: "Buy Food🌭",
        tag: "BuyFood",
        place: "buy",
        type: "tavern",
        store: "Tavern Cafe",
    },
    Shop: {
        name: "Shop",
        tag: "Shop",
        place: "door-entrance-shop",
        type: "tavern",
        store: "Shop",
    },
    FireStore: {
        name: "Fire Store",
        tag: "FireStore",
        place: "store",
        type: "volcano",
        store: "Fire Store",
    },
    Crafting: {
        name: "Crafting🪄",
        tag: "Crafting",
        place: "craft",
        time: 5,
        type: "volcano",
        effect: "/assets/effect/craft.gif",
        soundEffect: "/assets/effect/craftSfx.mp3",
    },
    Mining: {
        name: "Mining⛏️",
        tag: "Mining",
        place: "mining",
        stats: ["experience", "energy", "coins"],
        increment: [20, -10, 20],
        cost: 3,
        time: 5,
        type: "volcano",
        choose: ["BlueOre", "EmeraldStone", "BrickOfFire"],
        effect: "/assets/effect/mining.gif",
        soundEffect: "/assets/effect/miningSfx.mp3",
    },
    Crocheting: {
        name: "Crocheting🧶",
        tag: "Crocheting",
        place: "door-entrance-ice",
        stats: ["energy", "experience", "coins"],
        increment: [3, 3, 5],
        cost: 5,
        time: 5,
        type: "ice-kingdom",
        effect: "/assets/effect/crochet.gif",
    },
    PlayingSnow: {
        name: "Playing Snow☃️",
        tag: "PlayingSnow",
        place: "door-entrance-ice",
        stats: ["happiness"],
        increment: [10],
        time: 5,
        type: "ice-kingdom",
        effect: "/assets/effect/snowman.gif",
    },
    Meditating: {
        name: "Meditating🧘🏻",
        tag: "Meditating",
        place: "door-entrance-ice",
        stats: ["experience", "happiness", "hunger", "energy"],
        increment: [5, 5, 5, 5],
        time: 5,
        type: "ice-kingdom",
        effect: "/assets/effect/meditate.gif",
    },
    Cooking: {
        name: "Cooking🍳",
        tag: "Cooking",
        place: "cook",
        time: 5,
        type: "treehouse",
        effect: "/assets/effect/cookSfx.mp3",
    },
    Cleaning: {
        name: "Cleaning🧼",
        tag: "Cleaning",
        place: "clean",
        stats: ["happiness", "coins"],
        increment: [-3, 5],
        time: 5,
        cost: -3,
        type: "treehouse",
        effect: "/assets/effect/clean.gif",
        soundEffect: "/assets/effect/cleanSfx.mp3",
    },
    Sleeping: {
        name: "Sleeping🛌🏻",
        tag: "Sleeping",
        place: "bed",
        stats: ["energy"],
        increment: [20],
        time: 5,
        type: "treehouse",
        effect: "/assets/effect/sleep.gif",
        soundEffect: "/assets/effect/sleepSfx.mp3",
    },
    WatchTV: {
        name: "Watch TV📺",
        tag: "WatchTV",
        place: "tv",
        stats: ["happiness", "energy", "experience"],
        increment: [5, 5, 5],
        time: 5,
        type: "treehouse",
        effect: "/assets/effect/watch.gif",
        soundEffect: "/assets/effect/watchSfx.mp3",
    },
    Gardening: {
        name: "Gardening🧑🏻‍🌾",
        tag: "Gardening",
        place: "garden",
        stats: ["happiness", "energy", "coins"],
        increment: [5, 3, 10],
        time: 5,
        type: "map",
        choose: ["CornSeed", "TomatoSeed", "LettuceSeed", "SeedOfFlowerGlass"],
        effect: "/assets/effect/garden.gif",
        soundEffect: "/assets/effect/gardenSfx.mp3",
    },
    Bonfire: {
        name: "Bonfire🔥",
        tag: "Bonfire",
        place: "bonfire",
        stats: ["happiness", "hunger"],
        increment: [15, -5],
        time: 5,
        type: "cave",
        effect: "/assets/effect/bonfire.gif",
        soundEffect: "/assets/effect/bonfireSfx.mp3",
    },
};

export default activityData;
